### ISSUE TITLE
[REFACTOR] TimeSlider Layout

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1540] opened 2023-11-28 12:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the moment, the time slider is using the field for title and we cant have custom elements.

### Expected Behavior

Time slider should be configurable for title, and description.

- For title default is layer name if no configuration provided
- Optional description text (only for configuration)
- Put field name/alias for the use field by time dimension

Update configuration schema at the same time

**Comment by DamonU2** [comment] 2023-11-28 19:31
Duplicate of #1453?

**Comment by jolevesq** [comment] 2023-12-04 13:30
@DamonU2 you are right, I modified the purpose of the issue

**Closed** 2024-02-23 14:21 UTC
Labels: improvements: refactor, addition: core package
