### ISSUE TITLE
[BUG] WFS & OGC Feature API config: polygon feature layers do not display

### ISSUE THREAD

**Issue by MLAuger** [Canadian-Geospatial-Platform/geoview#2142] opened 2024-05-15 18:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Polygon feature layers do not appear (at all or partially) before you go into the “Data Table” menu and check the table. Then the data appears on the map.
This applies to the WFS and the OGC Feature API configs:

- https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/20-wfs.json
- https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/21-ogc-feature-api.json

![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/1ff40985-dc7d-430a-8304-be1f64de9b4a)
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/f0e7adf7-bb11-4e28-a2cc-9d5042540fa6)

### Expected Behavior

All polygon features should display as the layer is loaded.

**Comment by jolevesq** [comment] 2024-05-15 20:08
@MLAuger This was caused by a wrong character in the predefine layer filter. Should be fixed in our demo pages now. Thanks

**Closed by jolevesq** 2024-05-15 20:08 UTC
Labels: problem: bug, triage

**Comment by MLAuger** [comment] 2024-05-15 20:23
It's not totally fixed on my end. Only some of the polygons are displayed not all of them. Even after clearing my cache.

At the opening of the WFS layer: ![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/f1714488-1a67-4098-a0e9-a5a1f4535726)

After using the Data Table trick:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/c6b45af9-5a27-4815-8302-9dc44acd225e)

Same situation with the Feature API...
Before:
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/7d23e6c5-da65-4d98-b82f-f80db30aff43)


After: 
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/91547284/6bc83241-baa4-41ba-be14-f37e1d243797)
