### ISSUE TITLE
[BUG] [Layers]  Make draggable work in sort.. otherwise switch to using arrows.

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#2010] opened 2024-04-12 13:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Make draggable work in sort.. otherwise switch to using arrows.

**Comment by jolevesq** [comment] 2024-04-22 13:51
Duplicate of #1847

**Closed** 2024-04-30 18:34 UTC
Labels: problem: bug
