### ISSUE TITLE
[BUG] Geo.ca theme collision

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#843] opened 2023-01-25 19:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we integrate GeoView inside Geo.ca it creates style collision with Geo.ca Stylesheet.

### Expected Behavior

We should not have collision, we should wrapped our stylesheet inside our shell container and overwrite incoming style. If new style needs to be added, add a theme value for it.

### Steps To Reproduce

1. See the implementation here: https://wordpress.dev.geo.ca/wordpress/communities/flood-mapping/ (static maps)
2. See here https://wordpress.dev.geo.ca/wordpress/communities/flood-mapping/flood-map-gallery/historic-flood-events/

### Anything else?

![image](https://user-images.githubusercontent.com/3472990/214660039-411aa1ef-48b7-43e5-8741-86f3c61213ed.png)

- Purple footer bar expand arrow
- Purple nav bar icon with transparent background
- Big purple box on mouse over component
- Lost overview map open/close button

**Comment by jaredkinger** [comment] 2023-02-08 21:35
@jolevesq I will look into this

**Comment by jaredkinger** [comment] 2023-02-09 15:05
### Schema Error
**Page:** https://wordpress.dev.geo.ca/wordpress/communities/flood-mapping/ 
**Error Message:** "Map mapWM3: A schema error was found, check the console to see what is wrong"

You may already be aware of this. This is being caused by setting the zoom in the `viewSettings` to 3.5 instead of a integer like 3 or 4 in the data-config json of the wrapping div. This is affecting both maps.

Example of the relevant json below: 
```
"viewSettings": {
  "zoom": 3.5,
  "center": [
    -90,
    60
  ],
  "projection": 3978
}
```
Oddly enough despite the error this seems to render a 3.5 zoom as I tested both 3 and 4 and this zoom level seems to be in between.  Maybe the schema does accept a float here and the validation needs to reflect that?

### Purple Buttons
Previously on the WordPress site there was styling being applied to all `<button>` elements via a `.body-class button` rule. This would have caused the purple styling that you saw. I removed that style from the site last week so that's why this issue has disappeared.

I would recommend using a parent selector in all of the map's CSS rules. I can see the map is wrapped in a shell div that has a jss class. You could use that jss class from the shell div to better enforce the CSS rules. I didn't check every element but looking at the buttons they typically only have a single class selector being used for their styles. Example zoom in/out button styles:

```
.jss13 {
    color: #393939;
   /* more styles... */
}
````
If the shell class is jss1 then all of the jss styles should start with jss1 like this:

```
.jss1 .jss13 {
    color: #393939;
   /* more styles... */
}
````

### Overview map toggle arrow icon
This is an example of the markup for the toggle button with an HTML comment added by me:

```
<button type="button" title="Overview map">
  <div><!-- position: relative; is being applied to this div by the WordPress theme -->
    <div class="jss49">
      <div class="jss48 jss51" style="margin: 0px; padding: 0px; height: initial; min-width: initial;">
        <svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-14yq2cq" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ChevronLeftIcon"><path d="M15.41 7.41 14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path>
        </svg>
      </div>
    </div>
  </div>
</button>
```
There is unfortunately the following CSS coming the Phlox WordPress theme's base stylesheet:

```
a.button > *, 
button > *, 
input[type="button"] > *, 
.aux-button > * {
    position: relative;
}
```
Which will set `position: relative` on any immediate child of a button. This is throwing off the button icon. It doesn't appear that the unclassed div is necessary so that likely could be removed which would resolve this but I will add a CSS rule to override the theme's CSS above when applied to the .llwp-map.

**Comment by jolevesq** [comment] 2024-05-16 14:02
@jaredkinger is this still an issue on geo.ca?

**Comment by jaredkinger** [comment] 2024-05-16 14:09
@jolevesq This is not an issue anymore. You can close this.

**Closed** 2024-05-16 14:34 UTC
Labels: problem: bug, triage, experience: ui
