### ISSUE TITLE
[BUG] Data table esriDynamic

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1921] opened 2024-03-13 13:10 UTC
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
Data table not working for esriDynamic

**Expected Behavior**
A concise description of what you expected to happen.
Should works same way as esriFeature

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/esri-dynamic.html last map
2. Click on Data Table, then on any layer
3. See error

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by Alex-NRCan** [comment] 2024-04-08 18:32
This is likely a duplicate of #1855

**Closed** 2024-04-22 13:31 UTC
Labels: priority: high, problem: bug
