### ISSUE TITLE
[BUG] Font issue

### ISSUE THREAD

**Issue by namangera** [Canadian-Geospatial-Platform/geoview#2275] opened 2024-06-18 16:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get this error in the console
`downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: http://localhost:8080/b009a76ad6afe4ebd301.woff2`

### Steps To Reproduce

{
    "map": {
    "interaction": "dynamic",
    "viewSettings": {
    "initialView": {
      "layerIds": ["1"] 
    },
    "projection": 3978
    },
    "basemapOptions": {
      "shaded": true,
      "labeled": true,
      "basemapId": "transport"
    },
        "listOfGeoviewLayerConfig": [
            {
              "geoviewLayerId": "Hydro",
              "geoviewLayerName": {
                "en": "Hydro Location",
                "fr": "Hydro Location"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer/",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer/"
              },
              "geoviewLayerType": "esriDynamic",
              "initialSettings": {
                "states":{ 
                  "visible": false}
              },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "1"
                }
              ]
            },
            {
              "geoviewLayerId": "Flowlines",
              "geoviewLayerName": {
                "en": "Flowlines groupe",
                "fr": "Flowlines groupe"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/services/NRCan/chn_en/MapServer/WMSServer",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/services/NRCan/chn_en/MapServer/WMSServer"
              },
              "geoviewLayerType": "ogcWms",
              "initialSettings": {
                "states":{ 
                    "visible": false,
                    "legendCollaspsed": true}
                },
              "listOfLayerEntryConfig": [
                {
                  "entryType": "ogcWms",
                  "layerId": "6",
                  "layerName" : {
                    "en" : "Flowline (smaller-scale)",
                    "fr" : "Flowline (smaller-scale)"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "7",
                  "layerName" : {
                    "en" : "Flowline (small-scale)",
                    "fr" : "Flowline (small-scale)"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "8",
                  "layerName" : {
                    "en" : "Flowline (medium-scale)",
                    "fr" : "Flowline (medium-scale)"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "9",
                  "layerName" : {
                    "en" : "Flowline (large-scale)",
                    "fr" : "Flowline (large-scale)"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "10",
                  "layerName" : {
                    "en" : "Flow direction",
                    "fr" : "Flow direction"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "11",
                  "layerName" : {
                    "en" : "Geonames",
                    "fr" : "Geonames"
                  }
                },
                {
                  "entryType": "ogcWms",
                  "layerId": "12",
                  "layerName" : {
                    "en" : "Hydrolocation",
                    "fr" : "Hydrolocation"
                  }
                }
              ]
            },
            {
              "geoviewLayerId": "WaterBody",
              "geoviewLayerName": {
                "en": "Waterbody",
                "fr": "Waterbody"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer"
              },
              "geoviewLayerType": "esriDynamic",
              "initialSettings": {
                "states":{ 
                  "visible": false}
              },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "12"
                }
              ]
            },
            {
              "geoviewLayerId": "WorkUnit",
              "geoviewLayerName": {
                "en": "Work unit",
                "fr": "Work unit"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer"
              },
              "geoviewLayerType": "esriDynamic",
              "initialSettings": {
                "states":{ 
                  "visible": true}
              },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "9",
                  "source":{
                    "featureInfo": {
                      "queryable": false
                    }
                  }
                }
              ]
            },
            {
              "geoviewLayerId": "Drainage",
              "geoviewLayerName": {
                "en": "Drainage area",
                "fr": "Drainage area"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer"
              },
              "geoviewLayerType": "esriDynamic",
              "initialSettings": {
                "states":{ 
                  "visible": false}
              },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "10"
                }
              ]
            },
            {
              "geoviewLayerId": "Catchment",
              "geoviewLayerName": {
                "en": "Catchment",
                "fr": "Catchment"
              },
              "metadataAccessPath": {
                "en": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer",
                "fr": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/chn_en/MapServer"
              },
              "geoviewLayerType": "esriDynamic",
              "initialSettings": {
                "states":{ 
                  "visible": false}
              },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "11"
                }
              ]
            },
            {
              "geoviewLayerId": "landcover",
              "geoviewLayerName": {
                "en": "landcover",
                "fr": "landcover"
              },
              "metadataAccessPath": {
                "en": "https://datacube.services.geo.ca/ows/landcover",
                "fr": "https://datacube.services.geo.ca/ows/landcover"
              },
              "geoviewLayerType": "ogcWms",
              "initialSettings": {
                "states":{ 
                    "visible": false,
                    "legendCollaspsed": true}
                },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "landcover-2020",
                  "source":{
                    "style": ["official"]
                  }
                }
              ]
            },
            {
              "geoviewLayerId": "HRDEM",
              "geoviewLayerName": {
                "en": "HRDEM",
                "fr": "HRDEM"
              },
              "metadataAccessPath": {
                "en": "https://datacube.services.geo.ca/ows/elevation",
                "fr": "https://datacube.services.geo.ca/ows/elevation"
              },
              "geoviewLayerType": "ogcWms",
              "initialSettings": {
                  "states":{ 
                    "visible": false,
                    "legendCollaspsed": true}
                },
              "listOfLayerEntryConfig": [
                {
                  "entryType": "group",
                  "layerId": "WMS",
                  "layerName" : {
                    "en" : "HRDEM",
                    "fr" : "HRDEM"
                  },
                  "listOfLayerEntryConfig" : [
                    {
                      "layerId" : "dtm",
                      "layerName" : {
                        "en" : "dtm",  
                        "fr" : "dtm"
                      }
                    },
                    {
                      "layerId" : "dtm-slope",
                      "layerName" : {
                        "en" : "dtm-slope",  
                        "fr" : "dtm-slope"
                      }
                    },
                    {
                      "layerId" : "dtm-aspect",
                      "layerName" : {
                        "en" : "dtm-aspect",  
                        "fr" : "dtm-aspect"
                      }
                    },
                    {
                      "layerId" : "dtm-hillshade",
                      "layerName" : {
                        "en" : "dtm-hillshade",  
                        "fr" : "dtm-hillshade"
                      }
                    },
                    {
                      "layerId" : "dsm",
                      "layerName" : {
                        "en" : "dsm",  
                        "fr" : "dsm"
                      }
                    },
                    {
                      "layerId" : "dsm-slope",
                      "layerName" : {
                        "en" : "dsm-slope",  
                        "fr" : "dsm-slope"
                      }
                    },
                    {
                      "layerId" : "dsm-aspect",
                      "layerName" : {
                        "en" : "dsm-aspect",  
                        "fr" : "dsm-aspect"
                      }
                    },
                    {
                      "layerId" : "dsm-hillshade",
                      "layerName" : {
                        "en" : "dsm-hillshade",  
                        "fr" : "dsm-hillshade"
                      }
                    }
                  ]
                }
              ]
            },
            {
              "geoviewLayerId": "NHN",
              "geoviewLayerName": {
                "en": "NHN",
                "fr": "NHN"
              },
              "metadataAccessPath": {
                "en": "https://maps.geogratis.gc.ca/wms/hydro_network_en",
                "fr": "https://maps.geogratis.gc.ca/wms/hydro_network_fr"
              },
              "geoviewLayerType": "ogcWms",
              "initialSettings": {
                "states":{ 
                    "visible": false,
                    "legendCollaspsed": true                  
                  }
                },
              "listOfLayerEntryConfig": [
                {
                  "layerId": "hydro_network",
                  "layerName": {
                    "en": "NHN",
                    "fr": "NHN"
                  }
                }
              ]
            }
           
        ]  
    },
    "theme": "geo.ca",
    "appBar":{
      "tabs": {
        "core": ["geolocator", "export", "legend"]
      }
    },
    "navBar": ["zoom", "fullscreen", "home", "location"],
    "components": ["north-arrow"],
    "footerBar": {
      "tabs": {
        "core": ["layers", "details", "data-table"]
      }
    }
}

**Comment by jolevesq** [comment] 2024-06-25 19:02
Hi @namangera , we merged a PR to improve fonts. Can you test to see if your issue is resolved. If not can you give us more info like snapshot because we are not able to reproduce on our end

**Comment by namangera** [comment] 2024-07-03 15:49
Hi, using the july 2nd build I still get the error, here is a screenshot of it. Let me know how I can provide more info
![image](https://github.com/Canadian-Geospatial-Platform/geoview/assets/43800580/247aeb85-6f89-45a7-93e1-d6d162df8362)

**Comment by jolevesq** [comment] 2024-07-09 14:09
[@namagera](https://github.com/namangera), can you provide us a url to test outside the VPN?

**Comment by namangera** [comment] 2024-07-09 14:26
Sorry we don't have it available outside VPN.

**Comment by jolevesq** [comment] 2024-07-10 13:29
Font copied next to cgpv-main.js solved the problem. Release asset updated

**Closed by jolevesq** 2024-07-10 13:29 UTC
Labels: problem: bug
